package com.done.core.presentation.core.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFF54E1E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFF9E81)
val onPrimaryContainerLight = Color(0xFF2C0800)
val secondaryLight = Color(0xFF9A4526)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFBCA6)
val onSecondaryContainerLight = Color(0xFF561700)
val tertiaryLight = Color(0xFF725C00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBF9E16)
val onTertiaryContainerLight = Color(0xFF1B1400)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAFAFA)
val onBackgroundLight = Color(0xFF271813)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF271813)
val surfaceVariantLight = Color(0xFFFFDBCF)
val onSurfaceVariantLight = Color(0xFF5A4138)
val outlineLight = Color(0xFF8F7066)
val outlineVariantLight = Color(0xFFE3BFB3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF3D2D27)
val inverseOnSurfaceLight = Color(0xFFFFEDE8)
val inversePrimaryLight = Color(0xFFFFB59C)
val surfaceDimLight = Color(0xFFF0D4CC)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFAF1)
val surfaceContainerLowLight = Color(0xFFF6F0DF)
val surfaceContainerLight = Color(0xFFFFE9E3)
val surfaceContainerHighLight = Color(0xFFFEE2DA)
val surfaceContainerHighestLight = Color(0xFFF9DDD4)


// Extra colors
val doneBlue = Color(0xFF0062FF)
val doneGreen = Color(0xFF1fba00)
val doneRed = Color(0xFFE80000)
val doneOrange = Color(0xFFFC8E08)
val doneLighterOrange = Color(0xFFFFE9CD)
val doneBackgroundOrange = Color(0xFFFFF4F1)
